import { createContext, ReactNode, useContext, useEffect, useState } from 'react'

export type Language = 'en' | 'de'

const de: Record<string,string> = {
  'ENTERPRISE INTELLIGENCE & AUTOMATION':'UNTERNEHMENSINTELLIGENZ & AUTOMATISIERUNG','ENTERPRISE INTELLIGENCE':'UNTERNEHMENSINTELLIGENZ','Intelligent automation':'Intelligente Automatisierung','for the modern enterprise.':'für das moderne Unternehmen.','AI agents across Finance, Sales, Legal, Operations, and Marketing — all working in concert, all under your command.':'KI-Agenten für Finanzen, Vertrieb, Recht, Betrieb und Marketing – alle arbeiten gemeinsam und unter Ihrer Kontrolle.','Multi-agent AI workflows, end to end':'Durchgängige Multi-Agenten-KI-Workflows','AKEEM cut our cross-department reporting time by 80% and gave our executive team real-time intelligence they never had before.':'AKEEM reduzierte unsere abteilungsübergreifende Berichtszeit um 80 % und verschaffte unserem Führungsteam erstmals Echtzeit-Einblicke.',
  'Enterprise Platform':'Unternehmensplattform','Run your entire business':'Steuern Sie Ihr gesamtes Unternehmen','with one AI brain.':'mit einer einzigen KI.','Real-time intelligence across CRM, Finance, Sales, Legal, Marketing, and Operations — all in one unified platform.':'Echtzeit-Einblicke für CRM, Finanzen, Vertrieb, Recht, Marketing und Betrieb – alles auf einer einheitlichen Plattform.',
  'AI-powered across every department':'KI-Unterstützung in jeder Abteilung','Enterprise-grade security & compliance':'Sicherheit und Compliance auf Unternehmensniveau','Live business intelligence, always on':'Live Business Intelligence, rund um die Uhr','Integrates with your existing stack':'Integriert sich in Ihre bestehende Systemlandschaft','AI Business OS cut our reporting time by 80% and gave our executive team real-time intelligence they never had before.':'AI Business OS reduzierte unsere Berichtszeit um 80 % und verschaffte unserem Führungsteam erstmals Echtzeit-Einblicke.','CEO, Meridian Technologies':'Geschäftsführerin, Meridian Technologies',
  'Welcome back':'Willkommen zurück','Sign in to your organization account':'Melden Sie sich bei Ihrem Unternehmenskonto an','Continue with Google':'Mit Google fortfahren','Continue with LinkedIn':'Mit LinkedIn fortfahren','or sign in with email':'oder mit E-Mail anmelden','or sign up with email':'oder mit E-Mail registrieren','Work Email':'Geschäftliche E-Mail','Password':'Passwort','Enter your password':'Passwort eingeben','Remember me':'Angemeldet bleiben','Forgot password?':'Passwort vergessen?','Please wait…':'Bitte warten…','Sign In':'Anmelden','Create account':'Konto erstellen',"Don't have an account?":'Noch kein Konto?','Already have an account?':'Sie haben bereits ein Konto?','Sign in':'Anmelden','By signing in, you agree to our':'Mit Ihrer Anmeldung stimmen Sie unseren','Terms of Service':'Nutzungsbedingungen','Privacy Policy':'Datenschutzrichtlinie','and':'und','Create your account':'Konto erstellen','Start running your business with AI':'Steuern Sie Ihr Unternehmen mit KI','First Name':'Vorname','Last Name':'Nachname','Organization Name':'Unternehmensname','Timezone':'Zeitzone','Currency':'Währung','Reset your password':'Passwort zurücksetzen','We’ll send a reset link to your work email.':'Wir senden einen Link zum Zurücksetzen an Ihre geschäftliche E-Mail.','Send reset link':'Link zum Zurücksetzen senden','Reset-password API is not connected yet.':'Die API zum Zurücksetzen des Passworts ist noch nicht verbunden.','Back to sign in':'Zurück zur Anmeldung',
  'Workspace':'Arbeitsbereich','AI WORKSPACE':'KI-ARBEITSBEREICH','Dashboard':'Übersicht','AI Command Center':'KI-Kommandozentrale','AI Tasks':'KI-Aufgaben','AI Assistants Hub':'KI-Assistenten-Hub','ASSISTANTS':'ASSISTENTEN','CEO Assistant':'CEO-Assistent','Executive Assistant':'Executive-Assistent','Sales AI':'Vertriebs-KI','Finance AI':'Finanz-KI','Marketing AI':'Marketing-KI','Legal AI':'Rechts-KI','Operations AI':'Betriebs-KI','Customer Success AI':'Kundenerfolgs-KI','OPERATIONS':'BETRIEB','Approvals':'Genehmigungen','Automations':'Automatisierungen','BUSINESS':'UNTERNEHMEN','Finance':'Finanzen','SYSTEM':'SYSTEM','Settings':'Einstellungen','Administration':'Verwaltung','Search anything...':'Alles durchsuchen...','Notifications':'Benachrichtigungen','Sign out':'Abmelden',
  'Good morning, James':'Guten Morgen, James','Here’s what’s happening across your business today.':'Das passiert heute in Ihrem Unternehmen.','Ask AI Assistant':'KI-Assistenten fragen','Revenue':'Umsatz','Active Deals':'Aktive Geschäfte','Pending Tasks':'Offene Aufgaben','AI Hours Saved':'Eingesparte KI-Stunden','+8 this week':'+8 diese Woche','5 high priority':'5 mit hoher Priorität','+22% this month':'+22 % diesen Monat','Business overview':'Geschäftsübersicht','Last 6 months':'Letzte 6 Monate','AI activity':'KI-Aktivität','Qualified 12 new leads':'12 neue Leads qualifiziert','Completed cash flow forecast':'Cashflow-Prognose abgeschlossen','Reviewed vendor agreement':'Lieferantenvertrag geprüft','Prepared board brief':'Vorstandsinformation vorbereitet',
  'Your intelligent workspace for faster, better business decisions.':'Ihr intelligenter Arbeitsbereich für schnellere, bessere Geschäftsentscheidungen.','Manage and monitor your business operations in one place.':'Verwalten und überwachen Sie Ihren Geschäftsbetrieb an einem Ort.','Start new conversation':'Neue Unterhaltung starten','Create new':'Neu erstellen','Recent conversations':'Letzte Unterhaltungen','Overview':'Übersicht','Quarterly planning and priorities':'Quartalsplanung und Prioritäten','Review latest performance report':'Aktuellen Leistungsbericht prüfen','Prepare team status update':'Team-Statusbericht vorbereiten','Quick actions':'Schnellaktionen','Generate a report':'Bericht erstellen','Analyze performance':'Leistung analysieren','Create a summary':'Zusammenfassung erstellen','View recommendations':'Empfehlungen anzeigen',
  'Active project':'Aktives Projekt','Loading projects…':'Projekte werden geladen…','Select a project':'Projekt auswählen','Cancel':'Abbrechen','Create project':'Projekt erstellen','Refresh':'Aktualisieren','No project found. Create a project before using CEO Chat.':'Kein Projekt gefunden. Erstellen Sie vor der Nutzung des CEO-Chats ein Projekt.','Project name':'Projektname','Budget':'Budget','Start date':'Startdatum','Due date':'Fälligkeitsdatum','Description':'Beschreibung','Create & select':'Erstellen und auswählen','Creating…':'Wird erstellt…','Good morning, James. Your CEO Intelligence Briefing.':'Guten Morgen, James. Ihr CEO-Intelligence-Briefing.','Business Health':'Geschäftslage','Strong':'Stark','All KPIs green. Revenue +12.4% MoM.':'Alle KPIs im grünen Bereich. Umsatz +12,4 % zum Vormonat.','Priority Action':'Prioritäre Maßnahme','Sign Orbit Deal':'Orbit-Vertrag unterzeichnen','$680K — final negotiation today.':'680.000 $ – heute Abschlussverhandlung.','Board Readiness':'Vorstandsbereitschaft','6 Days':'6 Tage','Q1 deck 80% complete. 3 slides pending.':'Q1-Präsentation zu 80 % fertig. 3 Folien ausstehend.','Team Morale':'Teamstimmung','High':'Hoch','eNPS: 72. Attrition at record low.':'eNPS: 72. Fluktuation auf Rekordtief.','New Session':'Neue Sitzung','No active conversation':'Keine aktive Unterhaltung','Current session':'Aktuelle Sitzung','Online · Executive Strategy & Decision Support':'Online · Unternehmensstrategie & Entscheidungsunterstützung','Orbit Deal Workflow':'Orbit-Deal-Workflow','Strategic Analysis':'Strategische Analyse','Decision Support':'Entscheidungsunterstützung','Agent Orchestration':'Agenten-Orchestrierung','Loading conversation…':'Unterhaltung wird geladen…','Start a CEO intelligence session':'CEO-Intelligence-Sitzung starten','Select a project, then ask about progress, risks, priorities, or strategic decisions.':'Wählen Sie ein Projekt und fragen Sie nach Fortschritt, Risiken, Prioritäten oder strategischen Entscheidungen.','CEO Assistant is thinking…':'CEO-Assistent denkt nach…','Parallel agent analysis':'Parallele Agentenanalyse','Profitability, margin and cash-flow impact':'Rentabilität, Marge und Cashflow-Auswirkungen','IP ownership and liability exposure':'IP-Eigentum und Haftungsrisiken','View Agent →':'Agenten anzeigen →','Ask CEO AI about this project…':'CEO-KI zu diesem Projekt fragen…','Select or create a project to start chatting':'Projekt auswählen oder erstellen, um den Chat zu starten','Tasks':'Aufgaben','Reports':'Berichte','Activity':'Aktivität','Files':'Dateien','Decision Accuracy':'Entscheidungsgenauigkeit','Last 30 days':'Letzte 30 Tage','Active Tasks':'Aktive Aufgaben','3 high priority':'3 mit hoher Priorität','Reports Generated':'Erstellte Berichte','This quarter':'Dieses Quartal','Time Saved':'Eingesparte Zeit','This month':'Diesen Monat',
  'Please select or create a project first.':'Bitte wählen oder erstellen Sie zuerst ein Projekt.','Unable to load projects.':'Projekte konnten nicht geladen werden.','Unable to load conversation history.':'Der Unterhaltungsverlauf konnte nicht geladen werden.','Unable to create project.':'Projekt konnte nicht erstellt werden.','CEO Assistant could not respond.':'Der CEO-Assistent konnte nicht antworten.'
  ,'If this email exists, a reset link has been sent.':'Falls diese E-Mail existiert, wurde ein Link zum Zurücksetzen gesendet.'
}

const Context = createContext({ language: 'en' as Language, setLanguage: (_:Language)=>{} })

function translate(value:string, language:Language) {
  if(language==='en') return Object.entries(de).find(([,german])=>german===value)?.[0] ?? value
  if(de[value]) return de[value]
  return value.replace(/Updated (\d+) hours? ago/, (_,n)=>`Vor ${n} Stunde${n==='1'?'':'n'} aktualisiert`).replace(/Conversation #(\d+)/, 'Unterhaltung #$1')
}

export function LanguageProvider({children}:{children:ReactNode}) {
  const [language,setLanguageState]=useState<Language>(()=>localStorage.getItem('language')==='de'?'de':'en')
  const setLanguage=(value:Language)=>{localStorage.setItem('language',value);setLanguageState(value)}
  useEffect(()=>{
    document.documentElement.lang=language
    const apply=(root:ParentNode)=>{
      const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT); let node:Node|null
      while((node=walker.nextNode())) { const raw=node.nodeValue??'', trimmed=raw.trim(); if(trimmed){const next=translate(trimmed,language);if(next!==trimmed)node.nodeValue=raw.replace(trimmed,next)} }
      root.querySelectorAll?.('[placeholder],[title],[aria-label]').forEach(element=>['placeholder','title','aria-label'].forEach(attr=>{const value=element.getAttribute(attr);if(value)element.setAttribute(attr,translate(value,language))}))
    }
    apply(document.body)
    const observer=new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(node=>{if(node.nodeType===Node.ELEMENT_NODE)apply(node as Element);else if(node.nodeType===Node.TEXT_NODE&&node.nodeValue){const raw=node.nodeValue,trimmed=raw.trim(),next=translate(trimmed,language);if(next!==trimmed)node.nodeValue=raw.replace(trimmed,next)}})))
    observer.observe(document.body,{childList:true,subtree:true}); return()=>observer.disconnect()
  },[language])
  return <Context.Provider value={{language,setLanguage}}>{children}</Context.Provider>
}

export function useLanguage(){return useContext(Context)}
