import { FormEvent, useState } from 'react'
import { resetPassword } from '../services/auth'

export default function ResetPasswordPage({token,onDone}:{token:string;onDone:()=>void}){
  const [loading,setLoading]=useState(false),[error,setError]=useState(''),[complete,setComplete]=useState(false)
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),password=String(form.get('password')??''),confirm=String(form.get('confirm')??'');if(password!==confirm){setError('Passwords do not match.');return}setLoading(true);setError('');try{await resetPassword(token,password);setComplete(true);window.history.replaceState({},'',window.location.pathname)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to reset password.')}finally{setLoading(false)}}
  return <main className="flex min-h-screen items-center justify-center bg-slate-100 p-5"><section className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-6 shadow-xl"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#0A0E1A] font-serif text-xl font-bold text-[#c9a84c]">A</span><div><b className="block text-sm tracking-[.12em]">AKEEM</b><p className="text-[10px] text-slate-400">SECURE PASSWORD RESET</p></div></div>{complete?<div className="mt-8 text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-emerald-50 text-xl text-emerald-600">✓</span><h1 className="mt-4 text-xl font-bold">Password updated</h1><p className="mt-2 text-sm text-slate-500">You can now sign in with your new password.</p><button onClick={onDone} className="mt-6 w-full rounded-xl bg-blue-600 py-3 text-sm font-bold text-white">Continue to sign in</button></div>:<><h1 className="mt-8 text-xl font-bold">Choose a new password</h1><p className="mt-1 text-sm text-slate-500">Enter at least eight characters.</p><form onSubmit={submit} className="mt-6 space-y-4"><Field name="password" label="New password"/><Field name="confirm" label="Confirm password"/>{error&&<p className="rounded-lg bg-red-50 p-3 text-xs text-red-600">{error}</p>}<button disabled={loading} className="w-full rounded-xl bg-blue-600 py-3 text-sm font-bold text-white disabled:bg-blue-300">{loading?'Updating...':'Update password'}</button></form><button onClick={onDone} className="mt-4 w-full text-xs font-bold text-slate-500">Back to sign in</button></>}</section></main>
}
function Field({name,label}:{name:string;label:string}){return <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600">{label}</span><input required minLength={8} type="password" name={name} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-blue-400"/></label>}
