import { FormEvent, useEffect, useRef, useState } from 'react'
import { ApiRecord, OrganizationRole, organization, organizationMembers, organizationRoles, userProfile } from '../services/business'
import { changeMemberRole, changePassword, inviteMember, removeMember, updateOrganization, updatePreferences, updateProfile, uploadAvatar } from '../services/mutations'

type Tab='organization'|'profile'|'preferences'|'security'|'members'

export default function SettingsPage({role}:{role?:string}){
  const administrator=['owner','admin'].includes(String(role).toLowerCase())
  const [tab,setTab]=useState<Tab>(administrator?'organization':'profile')
  const [org,setOrg]=useState<ApiRecord>({})
  const [profile,setProfile]=useState<ApiRecord>({})
  const [members,setMembers]=useState<ApiRecord[]>([])
  const [roles,setRoles]=useState<OrganizationRole[]>([])
  const [loading,setLoading]=useState(true)
  const [saving,setSaving]=useState(false)
  const [error,setError]=useState('')
  const [success,setSuccess]=useState('')
  const avatarRef=useRef<HTMLInputElement>(null)
  const load=async()=>{setLoading(true);setError('');try{const [organizationData,profileData,memberData,roleData]=await Promise.all([organization(),userProfile(),administrator?organizationMembers():Promise.resolve([]),administrator?organizationRoles():Promise.resolve([])]);setOrg(organizationData);setProfile(profileData);setMembers(memberData);setRoles(roleData)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load settings.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[administrator])
  const run=async(task:()=>Promise<unknown>,message:string)=>{setSaving(true);setError('');setSuccess('');try{await task();setSuccess(message);window.dispatchEvent(new Event('settings:changed'));await load()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to save settings.')}finally{setSaving(false)}}

  async function saveOrganization(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await run(()=>updateOrganization({name:text(form,'name'),logoUrl:text(form,'logoUrl'),timezone:text(form,'timezone'),currency:text(form,'currency'),language:text(form,'language')}),'Organization updated.')}
  async function saveProfile(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await run(()=>updateProfile({firstName:text(form,'firstName'),lastName:text(form,'lastName'),phone:text(form,'phone')}),'Profile updated.')}
  async function savePreferences(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await run(()=>updatePreferences({language:text(form,'language'),timezone:text(form,'timezone'),emailNotifications:form.get('emailNotifications')==='on',browserNotifications:form.get('browserNotifications')==='on'}),'Preferences updated.')}
  async function savePassword(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget,form=new FormData(formElement),next=text(form,'newPassword');if(next!==text(form,'confirmPassword')){setError('New passwords do not match.');return}await run(()=>changePassword({currentPassword:text(form,'currentPassword'),newPassword:next}),'Password changed.');formElement.reset()}
  async function invite(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget,form=new FormData(formElement);await run(()=>inviteMember({email:text(form,'email'),roleId:Number(form.get('roleId'))}),'Invitation sent.');formElement.reset()}
  async function avatar(event:React.ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){setError('Avatar must be 5 MB or smaller.');return}await run(()=>uploadAvatar(file),'Avatar updated.');event.target.value=''}

  const tabs:Tab[]=administrator?['organization','profile','preferences','security','members']:['profile','preferences','security']
  return <div className="mx-auto max-w-5xl"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-blue-600">Account</p><h1 className="mt-1 text-2xl font-bold">Settings</h1><p className="mt-1 text-sm text-slate-500">Manage your organization, personal profile, preferences, and team.</p></div><div className="mt-5 flex gap-1 overflow-x-auto rounded-xl border border-slate-200 bg-white p-1">{tabs.map(item=><button key={item} onClick={()=>{setTab(item);setError('');setSuccess('')}} className={`whitespace-nowrap rounded-lg px-4 py-2 text-xs font-semibold capitalize ${tab===item?'bg-[#0A0E1A] text-[#c9a84c]':'text-slate-500 hover:bg-slate-50'}`}>{item}</button>)}</div>
    {error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-xs text-red-600">{error}</p>}{success&&<p className="mt-4 rounded-xl bg-emerald-50 p-3 text-xs text-emerald-700">{success}</p>}
    {loading?<div className="mt-5 h-64 animate-pulse rounded-xl bg-slate-200"/>:<section className="mt-5 rounded-xl border border-slate-200 bg-white p-5 shadow-sm">{tab==='organization'&&<OrganizationForm key={String(org.id??'org')} data={org} saving={saving} onSubmit={saveOrganization}/>} {tab==='profile'&&<ProfileForm key={String(profile.id??'profile')} data={profile} saving={saving} avatarRef={avatarRef} onAvatar={avatar} onSubmit={saveProfile}/>} {tab==='preferences'&&<PreferencesForm data={profile} saving={saving} onSubmit={savePreferences}/>} {tab==='security'&&<SecurityForm saving={saving} onSubmit={savePassword}/>} {tab==='members'&&<MembersPanel items={members} roles={roles} currentUserId={Number(profile.id)} saving={saving} onInvite={invite} onRemove={member=>void run(()=>removeMember(Number(member.membershipId??member.id)), 'Member removed.')} onRole={(member,roleId)=>void run(()=>changeMemberRole(Number(member.membershipId??member.id),roleId),'Member role updated.')}/>}</section>}
  </div>
}

function OrganizationForm({data,saving,onSubmit}:{data:ApiRecord;saving:boolean;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){return <form onSubmit={onSubmit}><Heading title="Organization" text="Company-wide defaults used by finance, reports, and AI context."/><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field name="name" label="Organization name" defaultValue={String(data.name??'')}/><Field name="logoUrl" label="Logo URL" type="url" defaultValue={String(data.logoUrl??'')}/><Field name="timezone" label="Timezone" defaultValue={String(data.timezone??'Europe/Berlin')}/><Field name="currency" label="Currency" defaultValue={String(data.currency??'EUR')}/><label><span className="mb-1 block text-xs text-slate-600">Language</span><select name="language" defaultValue={String(data.language??'en')} className="h-10 w-full rounded-lg border border-slate-200 px-3 text-sm"><option value="en">English</option><option value="de">German</option></select></label></div><Save saving={saving}/></form>}
function ProfileForm({data,saving,avatarRef,onAvatar,onSubmit}:{data:ApiRecord;saving:boolean;avatarRef:React.RefObject<HTMLInputElement>;onAvatar:(event:React.ChangeEvent<HTMLInputElement>)=>void;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){return <form onSubmit={onSubmit}><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><Heading title="Personal profile" text="Update the identity displayed throughout your workspace."/><div><input ref={avatarRef} type="file" accept="image/*" onChange={event=>void onAvatar(event)} className="hidden"/><button type="button" onClick={()=>avatarRef.current?.click()} className="rounded-lg border border-blue-200 bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">Upload avatar</button></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field name="firstName" label="First name" defaultValue={String(data.firstName??'')}/><Field name="lastName" label="Last name" defaultValue={String(data.lastName??'')}/><Field name="phone" label="Phone" defaultValue={String(data.phone??'')}/><Field name="email" label="Email" type="email" disabled defaultValue={String(data.email??'')}/></div><Save saving={saving}/></form>}
function PreferencesForm({data,saving,onSubmit}:{data:ApiRecord;saving:boolean;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){const preferences=(data.preferences&&typeof data.preferences==='object'?data.preferences:{}) as ApiRecord;return <form onSubmit={onSubmit}><Heading title="Preferences" text="Control localization and notification delivery."/><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field name="timezone" label="Timezone" defaultValue={String(preferences.timezone??data.timezone??'Europe/Berlin')}/><label><span className="mb-1 block text-xs text-slate-600">Language</span><select name="language" defaultValue={String(preferences.language??data.language??'en')} className="h-10 w-full rounded-lg border border-slate-200 px-3 text-sm"><option value="en">English</option><option value="de">German</option></select></label><Toggle name="emailNotifications" label="Email notifications" defaultChecked={Boolean(preferences.emailNotifications??true)}/><Toggle name="browserNotifications" label="Browser notifications" defaultChecked={Boolean(preferences.browserNotifications??true)}/></div><Save saving={saving}/></form>}
function SecurityForm({saving,onSubmit}:{saving:boolean;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){return <form onSubmit={onSubmit}><Heading title="Password" text="Use at least eight characters for your new password."/><div className="mt-5 max-w-md space-y-4"><Field name="currentPassword" label="Current password" type="password" required/><Field name="newPassword" label="New password" type="password" minLength={8} required/><Field name="confirmPassword" label="Confirm new password" type="password" minLength={8} required/></div><Save saving={saving}/></form>}
function MembersPanel({items,roles,currentUserId,saving,onInvite,onRemove,onRole}:{items:ApiRecord[];roles:OrganizationRole[];currentUserId:number;saving:boolean;onInvite:(event:FormEvent<HTMLFormElement>)=>void;onRemove:(member:ApiRecord)=>void;onRole:(member:ApiRecord,roleId:number)=>void}){const assignable=roles.filter(role=>role.name.toLowerCase()!=='owner');return <><Heading title="Organization members" text="Invite teammates and manage membership access."/><form onSubmit={onInvite} className="mt-5 flex flex-col gap-2 rounded-xl bg-slate-50 p-3 sm:flex-row"><input required name="email" type="email" placeholder="member@example.com" className="h-10 min-w-0 flex-1 rounded-lg border border-slate-200 px-3 text-sm"/><select required name="roleId" className="h-10 rounded-lg border border-slate-200 px-3 text-sm">{assignable.map(role=><option key={role.id} value={role.id}>{role.name}</option>)}</select><button disabled={saving||!assignable.length} className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-bold text-white disabled:bg-blue-300">Invite</button></form><div className="mt-4 divide-y divide-slate-100">{items.map((member,index)=>{const user=(member.user&&typeof member.user==='object'?member.user:{}) as ApiRecord;const role=(member.role&&typeof member.role==='object'?member.role:{}) as ApiRecord;const isSelf=Number(member.userId??user.id)===currentUserId;return <div key={String(member.membershipId??member.id??index)} className="flex flex-col gap-2 py-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><b className="block truncate text-xs">{String([user.firstName,user.lastName].filter(Boolean).join(' ')||user.email||'Member')}{isSelf?' (you)':''}</b><p className="text-[10px] text-slate-400">{String(user.email??'')} · {String(role.name??'Member')}</p></div><div className="flex items-center gap-2"><select disabled={isSelf||saving} value={Number(member.roleId)||''} onChange={event=>onRole(member,Number(event.target.value))} aria-label="Member role" className="h-8 rounded-lg border border-slate-200 px-2 text-xs disabled:bg-slate-100">{roles.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select><button disabled={isSelf||saving} onClick={()=>{if(window.confirm('Remove this member?'))onRemove(member)}} className="rounded-lg bg-red-50 px-3 py-2 text-[10px] font-bold text-red-600 disabled:text-slate-300">Remove</button></div></div>})}{!items.length&&<p className="py-8 text-center text-xs text-slate-400">No members found.</p>}</div></>}
function Heading({title,text}:{title:string;text:string}){return <div><h2 className="text-sm font-bold">{title}</h2><p className="mt-1 text-xs text-slate-400">{text}</p></div>}
function Field({label,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label><span className="mb-1 block text-xs text-slate-600">{label}</span><input {...props} className="h-10 w-full rounded-lg border border-slate-200 px-3 text-sm outline-none focus:border-blue-400 disabled:bg-slate-50 disabled:text-slate-400"/></label>}
function Toggle({label,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label className="flex items-center justify-between rounded-lg border border-slate-200 p-3 text-xs font-medium text-slate-600">{label}<input type="checkbox" {...props} className="h-4 w-4"/></label>}
function Save({saving}:{saving:boolean}){return <div className="mt-6 flex justify-end"><button disabled={saving} className="rounded-lg bg-blue-600 px-5 py-2.5 text-xs font-bold text-white disabled:bg-blue-300">{saving?'Saving...':'Save changes'}</button></div>}
function text(form:FormData,key:string){return String(form.get(key)??'')}
