import { crmList, organizationRoles, ApiRecord } from '../services/business'
import { FormEvent, useEffect, useState } from 'react'
import { createApproval, createAutomation, createBudget, createCrm, createIntegration, createInvoice, createTransaction, inviteMember, updateOrganization, updateProfile } from '../services/mutations'
import { createAITask } from '../services/p0'

type Props={module:string;section:string;projectId?:number;onClose:()=>void;onDone:()=>void}

export default function CreateResourcePanel({module,section,projectId,onClose,onDone}:Props){const [loading,setLoading]=useState(false),[error,setError]=useState('')
  const [lookups,setLookups]=useState<Record<string,ApiRecord[]>>({}),[optionsLoading,setOptionsLoading]=useState(true)
  useEffect(()=>{let active=true;async function load(){try{const needed=fieldsFor(module,section).map(field=>field.name);const data:Record<string,ApiRecord[]>={};if(needed.includes('companyId'))data.companyId=await crmList('companies');if(needed.includes('contactId'))data.contactId=await crmList('contacts');if(needed.includes('roleId'))data.roleId=(await organizationRoles()).filter(role=>role.name.toLowerCase()!=='owner');if(active)setLookups(data)}catch(reason){if(active)setError(reason instanceof Error?reason.message:'Unable to load choices.')}finally{if(active)setOptionsLoading(false)}}void load();return()=>{active=false}},[module,section])
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setLoading(true);setError('');const f=new FormData(event.currentTarget),s=(key:string)=>String(f.get(key)??''),n=(key:string)=>s(key).trim()===''?undefined:Number(s(key))
    try{if(module==='tasks'&&!projectId)throw new Error('Select a project before creating a task.');
      if(module==='tasks')await createAITask({projectId,title:s('title'),description:s('description'),assistant:s('assistant'),priority:s('priority'),executionMode:s('executionMode'),runNow:s('runNow')==='true',input:{}})
      if(module==='approvals')await createApproval({projectId,title:s('title'),type:s('type'),amount:n('amount'),currency:s('currency'),description:s('description')})
      if(module==='automations')await createAutomation({projectId,name:s('name'),description:s('description'),trigger:{cron:s('cron')},actions:[{type:'generate_report',payload:{title:s('name'),assistant:s('assistant')}}],enabled:true})
      if(module==='crm'&&section==='companies')await createCrm('companies',{name:s('name'),domain:s('domain'),industry:s('industry'),phone:s('phone'),website:s('website')})
      if(module==='crm'&&section==='contacts')await createCrm('contacts',{companyId:n('companyId'),firstName:s('firstName'),lastName:s('lastName'),email:s('email'),phone:s('phone'),jobTitle:s('jobTitle'),lifecycleStage:'lead'})
      if(module==='crm'&&section==='deals')await createCrm('deals',{name:s('name'),companyId:n('companyId'),contactId:n('contactId'),value:n('value'),currency:s('currency'),expectedCloseDate:s('expectedCloseDate')||undefined,status:'open'})
      if(module==='finance'&&section==='transactions')await createTransaction({projectId,type:s('type') as 'income'|'expense'|'transfer',amount:n('amount')??0,currency:s('currency'),description:s('description'),status:'cleared',transactionDate:new Date().toISOString()})
      if(module==='finance'&&section==='invoices')await createInvoice({projectId,companyId:n('companyId'),status:'draft',issueDate:s('issueDate')||undefined,dueDate:s('dueDate')||undefined,currency:s('currency'),notes:s('notes'),items:[{description:s('itemDescription'),quantity:n('quantity')??1,unitPrice:n('unitPrice')??0,taxRate:Number(f.get('taxRate'))||0}]})
      if(module==='finance'&&section==='budgets')await createBudget({projectId,name:s('name'),amount:n('amount')??0,currency:s('currency'),periodStart:s('periodStart')||undefined,periodEnd:s('periodEnd')||undefined})
      if(module==='settings'&&section==='organization')await updateOrganization({name:s('name'),timezone:s('timezone'),currency:s('currency'),language:s('language')})
      if(module==='settings'&&section==='members')await inviteMember({email:s('email'),roleId:n('roleId')})
      if(module==='settings'&&section==='profile')await updateProfile({firstName:s('firstName'),lastName:s('lastName'),phone:s('phone')})
      if(module==='admin'&&section==='integrations')await createIntegration({provider:s('provider'),displayName:s('displayName'),status:'connected',credentials:{accessToken:s('accessToken')},settings:{}})
      onDone();onClose()
    }catch(reason){setError(reason instanceof Error?reason.message:'Unable to save.')}finally{setLoading(false)}}
  const fields=fieldsFor(module,section)
  if(!fields.length)return null
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/40 p-0 sm:items-center sm:p-4"><form onSubmit={submit} className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-t-2xl bg-white p-5 shadow-2xl sm:rounded-2xl"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">{module==='settings'?'Update':'Create'} {section||module}</h2><button type="button" onClick={onClose} className="rounded-lg px-3 py-1 text-slate-400 hover:bg-slate-100">✕</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{fields.map(field=><label key={field.name} className={field.wide?'sm:col-span-2':''}><span className="mb-1 block text-xs font-medium capitalize text-slate-600">{field.label}</span>{['companyId','contactId','roleId'].includes(field.name)?<select name={field.name} required={field.required} disabled={optionsLoading} className="h-10 w-full rounded-lg border border-slate-200 px-3 text-sm"><option value="">{optionsLoading?'Loading...':field.required?'Select an option':'None'}</option>{(lookups[field.name]??[]).map(row=><option key={String(row.id)} value={String(row.id)}>{String(row.name??([row.firstName,row.lastName].filter(Boolean).join(' ')||row.email||row.id))}</option>)}</select>:field.options?<select name={field.name} required={field.required} className="h-10 w-full rounded-lg border border-slate-200 px-3 text-sm">{field.options.map(option=><option key={option}>{option}</option>)}</select>:<input name={field.name} type={field.type??'text'} step={field.type==='number'?'any':undefined} required={field.required} defaultValue={field.value} placeholder={field.placeholder} className="h-10 w-full rounded-lg border border-slate-200 px-3 text-sm"/>}</label>)}</div>{error&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-xs text-red-600">{error}</p>}<div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border border-slate-200 px-4 py-2 text-xs font text-xs font-semibold">Cancel</button><button disabled={loading||optionsLoading} className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-bold text-white disabled:bg-blue-300">{loading?'Saving…':'Save'}</button></div></form></div>}
type Field={name:string;label:string;type?:string;required?:boolean;placeholder?:string;value?:string;options?:string[];wide?:boolean}
function fieldsFor(module:string,section:string):Field[]{
  if(module==='tasks')return[{name:'title',label:'Title',required:true},{name:'assistant',label:'Assistant',required:true,options:['ceo','executive','sales','finance','marketing','legal','operations','customer-success']},{name:'priority',label:'Priority',options:['low','medium','high']},{name:'executionMode',label:'Execution mode',options:['suggest','auto']},{name:'runNow',label:'Run immediately',options:['true','false']},{name:'description',label:'Description',required:true,wide:true}]
  if(module==='approvals')return[{name:'title',label:'Title',required:true},{name:'type',label:'Type',required:true,options:['contract','budget','general']},{name:'amount',label:'Amount',type:'number'},{name:'currency',label:'Currency',value:'PKR'},{name:'description',label:'Description',wide:true}]
  if(module==='automations')return[{name:'name',label:'Name',required:true},{name:'cron',label:'Cron schedule',required:true,value:'0 9 * * 1'},{name:'assistant',label:'Assistant',options:['executive','ceo','sales','finance']},{name:'description',label:'Description',wide:true}]
  if(module==='crm'&&section==='companies')return[{name:'name',label:'Name',required:true},{name:'domain',label:'Domain'},{name:'industry',label:'Industry'},{name:'phone',label:'Phone'},{name:'website',label:'Website',wide:true}]
  if(module==='crm'&&section==='contacts')return[{name:'firstName',label:'First name',required:true},{name:'lastName',label:'Last name',required:true},{name:'email',label:'Email',type:'email'},{name:'phone',label:'Phone'},{name:'companyId',label:'Company'},{name:'jobTitle',label:'Job title'}]
  if(module==='crm'&&section==='deals')return[{name:'name',label:'Deal name',required:true},{name:'value',label:'Value',type:'number'},{name:'companyId',label:'Company ID',type:'number'},{name:'contactId',label:'Contact'},{name:'currency',label:'Currency',value:'PKR'},{name:'expectedCloseDate',label:'Expected close',type:'date'}]
  if(module==='finance'&&section==='transactions')return[{name:'type',label:'Type',options:['income','expense','transfer']},{name:'amount',label:'Amount',type:'number',required:true},{name:'currency',label:'Currency',value:'PKR'},{name:'description',label:'Description'}]
  if(module==='finance'&&section==='budgets')return[{name:'name',label:'Name',required:true},{name:'amount',label:'Amount',type:'number',required:true},{name:'currency',label:'Currency',value:'PKR'},{name:'periodStart',label:'Period start',type:'date'},{name:'periodEnd',label:'Period end',type:'date'}]
  if(module==='finance'&&section==='invoices')return[{name:'companyId',label:'Company ID',type:'number'},{name:'currency',label:'Currency',value:'PKR'},{name:'issueDate',label:'Issue date',type:'date'},{name:'dueDate',label:'Due date',type:'date'},{name:'itemDescription',label:'Item description',required:true},{name:'quantity',label:'Quantity',type:'number',value:'1'},{name:'unitPrice',label:'Unit price',type:'number',required:true},{name:'taxRate',label:'Tax rate',type:'number',value:'0'},{name:'notes',label:'Notes',wide:true}]
  if(module==='settings'&&section==='organization')return[{name:'name',label:'Organization name'},{name:'timezone',label:'Timezone',value:'Europe/Berlin'},{name:'currency',label:'Currency',value:'EUR'},{name:'language',label:'Language',options:['en','de']}]
  if(module==='settings'&&section==='members')return[{name:'email',label:'Email',type:'email',required:true},{name:'roleId',label:'Role',required:true}]
  if(module==='settings'&&section==='profile')return[{name:'firstName',label:'First name'},{name:'lastName',label:'Last name'},{name:'phone',label:'Phone'}]
  if(module==='admin'&&section==='integrations')return[{name:'provider',label:'Provider',required:true},{name:'displayName',label:'Display name',required:true},{name:'accessToken',label:'Access token',type:'password',required:true,wide:true}]
  return[]
}
