import { useEffect, useState } from 'react'
import Icon from './Icon'
import { getNotifications, readAllNotifications, readNotification } from '../services/p0'
type Notice={id:number;title:string;message:string;read:boolean;createdAt:string}
export default function NotificationsMenu(){const [open,setOpen]=useState(false),[items,setItems]=useState<Notice[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('')
  const load=async()=>{setLoading(true);try{const value=await getNotifications(1,20) as {items?:Notice[]};setItems(Array.isArray(value)?value:value.items??[])}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load notifications.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);const unread=items.filter(item=>!item.read).length
  const markOne=async(item:Notice)=>{if(item.read)return;await readNotification(item.id);setItems(list=>list.map(value=>value.id===item.id?{...value,read:true}:value))}
  const markAll=async()=>{await readAllNotifications();setItems(list=>list.map(item=>({...item,read:true})))}
  return <div className="relative"><button onClick={()=>setOpen(value=>!value)} aria-label="Notifications" className="relative rounded-lg p-2 hover:bg-slate-100"><Icon name="bell" className="h-4 w-4 text-slate-500"/>{unread>0&&<span className="absolute right-0 top-0 flex h-4 min-w-4 items-center justify-center rounded-full bg-red-500 px-1 text-[9px] font-bold text-white">{unread}</span>}</button>{open&&<div className="absolute right-0 top-11 z-50 w-[min(320px,calc(100vw-24px))] overflow-hidden rounded-xl border border-slate-200 bg-white shadow-xl"><header className="flex items-center justify-between border-b border-slate-100 px-4 py-3"><b className="text-sm">Notifications</b><button onClick={()=>void markAll()} className="text-[11px] font-semibold text-blue-600">Mark all read</button></header><div className="max-h-80 overflow-y-auto">{loading?<p className="p-6 text-center text-xs text-slate-400">Loading data…</p>:error?<p className="p-4 text-xs text-red-500">{error}</p>:items.length?items.map(item=><button key={item.id} onClick={()=>void markOne(item)} className={`block w-full border-b border-slate-50 px-4 py-3 text-left hover:bg-slate-50 ${item.read?'':'bg-amber-50/40'}`}><p className="text-xs font-bold text-slate-700">{item.title}</p><p className="mt-1 text-[11px] text-slate-500">{item.message}</p><p className="mt-1 text-[10px] text-slate-400">{new Date(item.createdAt).toLocaleString()}</p></button>):<p className="p-6 text-center text-xs text-slate-400">No notifications</p>}</div></div>}</div>}
